version: '3.7'
services:
    traefik:
      image: ${IMAGE_TRAEFIK}
      container_name: ${APP}_traefik
      security_opt:
        - no-new-privileges:true
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.entrypoints=https"
        - "traefik.http.routers.traefik.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.middlewares=traefik-auth"
        - "traefik.http.services.traefik-traefik.loadbalancer.server.port=888"
        - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$A1rHw/yS$$tPBoVHzso7Bj2RF6O/CDr."
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        # global redirect to https
        - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
        - "traefik.http.routers.http-catchall.entrypoints=http"
        - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      ports:
        - 80:80
        - 443:443
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./data/traefik.yml:/traefik.yml:ro
        - ./data/acme.json:/acme.json
      networks:
        - glpi-frontend

    server:
      container_name: ${APP}_server
      image: ${IMAGE_SERVER}
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.glpi.entrypoints=https"
        - "traefik.http.routers.glpi.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.glpi.tls=true"
        - "traefik.http.routers.glpi.tls.certresolver=letsEncrypt"
        - "traefik.http.services.glpi-service.loadbalancer.server.port=80"
        - "traefik.docker.network=glpi-frontend"
      environment:
        GLPI_LANG: pt_BR
        db_HOST: mariadb-glpi
        db_PORT: 3306
        db_DATABASE: ${MYSQL_DATABASE}
        db_USER: ${MYSQL_USER}
        db_PASSWORD: ${MYSQL_PASSWORD}
        VERSION: "9.5.1"
        PLUGINS: "all"
      depends_on:
        - mariadb-glpi
      expose:
        - 80
      # ports:
      #   - 8090:80
      volumes:
        - glpi-volume-files:/var/www/html/files
        - glpi-volume-plugins:/var/www/html/plugins
      networks:
        - glpi-frontend
        - glpi-backend

    crond:
        image: ${IMAGE_CRON}
        container_name: ${APP}_cron
        restart: unless-stopped
        depends_on:
          - mariadb-glpi
        environment:
          db_HOST: mariadb-glpi
          db_PORT: 3306
          db_DATABASE: ${MYSQL_DATABASE}
          db_USER: ${MYSQL_USER}
          db_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
          - glpi-volume-files:/var/www/html/files
          - glpi-volume-plugins:/var/www/html/plugins
        networks:
          - glpi-backend

    mariadb-glpi:
      container_name: ${APP}_db
      image: ${IMAGE_DB}
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_RANDOM_ROOT_PASSWORD: 1
      expose:
        - 3306
      volumes:
        - db-glpi-volume:/var/lib/mysql
      networks:
        - glpi-backend

volumes:
  glpi-volume-files:
  glpi-volume-plugins:
  db-glpi-volume:

networks:
  glpi-frontend:
    name: ${APP}_frontend_net
  glpi-backend:
    name: ${APP}_backend_net
